### ISSUE TITLE
Figure treatment

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-redesign-prototype#13]
Not sure if the background behind the figure is supposed to be shaded.  

![images_prototype_figure_treatment](https://cloud.githubusercontent.com/assets/6391769/9265245/4642e180-41f6-11e5-8d1e-a5a3989f37e2.png)

Will the template support the following [restructured text figure and image options](http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure)? 

Optionally, the image link block may contain a flat field list, the image options. For example:

.. image:: picture.jpeg
   :height: 100px
   :width: 200 px
   :scale: 50 %
   :alt: alternate text
   :align: right

**Comment by ktbartholomew** [comment]
The shaded background is intentional, to offset the figure from the content around it. That specific styling may change.

The markup for that is exactly what's generated when a figure is created in Sphinx, including the caption. I would advise against adding the presentational parameters you mentioned though, as they create style declarations that are not responsive to different screen sizes and are impossible to override with CSS.

**Comment by meker12** [comment]
per Keith's note above.   Do not use the RST presentation images to style images.   Log issues about image rendering or formatting with Engineering or UX.

@ktbartholomew @technabors  Where do we log issues related to CSS?

**Comment by ktbartholomew** [comment]
@meker12 yes, nexus-control
